export interface BibleBook {
  name: string
  abbreviation: string
  testament: 'OT' | 'NT'
  section: string
  author: string
  date: string
  audience: string
  themes: string[]
  preface: string
}

export const BIBLE_BOOKS: BibleBook[] = [
  // ── OLD TESTAMENT: TORAH / PENTATEUCH ──────────────────────
  {
    name: 'Genesis',
    abbreviation: 'Gen',
    testament: 'OT',
    section: 'Torah',
    author: 'Moses (traditional attribution)',
    date: 'c. 1400–1200 BC (events span creation to c. 1800 BC)',
    audience: 'Israel in the wilderness, newly liberated from Egypt',
    themes: ['Creation', 'Fall', 'Covenant', 'Providence', 'Redemption'],
    preface: 'The foundational book of Scripture, Genesis answers humanity\'s deepest questions: Where did everything come from? Why is everything broken? And is there any hope? Beginning with creation and ending with Israel in Egypt, it traces the thread of God\'s covenant promise through a deeply human story of faith, failure, and grace. Every major theme of Scripture — sin, sacrifice, election, promise — is first seen here. Jesus is the seed of the woman who will crush the serpent\'s head, the true offspring of Abraham through whom all nations will be blessed.',
  },
  {
    name: 'Exodus',
    abbreviation: 'Exod',
    testament: 'OT',
    section: 'Torah',
    author: 'Moses',
    date: 'c. 1400–1200 BC',
    audience: 'Israel in the wilderness',
    themes: ['Liberation', 'The Name of God', 'Passover', 'Law', 'Tabernacle', 'Covenant'],
    preface: 'The defining event of Old Testament history: God hears the cry of his enslaved people and comes down to rescue them through a man named Moses. Exodus gives us God\'s name (YHWH — "I AM WHO I AM"), the Passover (the lamb whose blood protects from judgment), the Ten Commandments, and the detailed instructions for the Tabernacle — the place where God would dwell among his people. Every element of Exodus finds its fulfillment in Christ: the Passover lamb, the manna from heaven, the water from the rock, the presence of God in the wilderness.',
  },
  {
    name: 'Leviticus',
    abbreviation: 'Lev',
    testament: 'OT',
    section: 'Torah',
    author: 'Moses',
    date: 'c. 1400–1200 BC',
    audience: 'The priestly community of Israel',
    themes: ['Holiness', 'Sacrifice', 'Atonement', 'Purity', 'Priesthood'],
    preface: 'Leviticus is the most neglected book in many reading plans and one of the most important in the Bible. Its central command — "You shall be holy, for I the LORD your God am holy" — is the heartbeat of all biblical ethics. The elaborate sacrificial system is not primitive religion; it is a detailed theology of atonement, teaching Israel (and us) how seriously God takes sin and how completely sacrifice must cover it. The Day of Atonement (Yom Kippur) in chapter 16 is the clearest Old Testament picture of what Christ accomplished on the cross: one sacrifice, once for all.',
  },
  {
    name: 'Numbers',
    abbreviation: 'Num',
    testament: 'OT',
    section: 'Torah',
    author: 'Moses',
    date: 'c. 1400–1200 BC',
    audience: 'Israel in the wilderness',
    themes: ['Faithfulness', 'Wilderness', 'Rebellion', 'Providence', 'Covenant'],
    preface: 'Numbers is a book of journeying — and of the terrible cost of faithlessness. Israel stands on the edge of the Promised Land and turns back in fear. A generation wanders and dies in the wilderness. Yet God\'s faithfulness does not fail even when Israel\'s does. Paul cites Numbers as a warning to the church: these things were written down as examples for us, so that we would not desire evil as they did (1 Corinthians 10:6–11). The bronze serpent on the pole, which healed those who looked at it, becomes for Jesus himself an image of the cross (John 3:14–15).',
  },
  {
    name: 'Deuteronomy',
    abbreviation: 'Deut',
    testament: 'OT',
    section: 'Torah',
    author: 'Moses',
    date: 'c. 1400–1200 BC',
    audience: 'Israel on the edge of the Promised Land',
    themes: ['Covenant renewal', 'Love for God', 'Obedience', 'Remembrance', 'Law'],
    preface: 'Deuteronomy is Moses\' farewell address — a great sermon preached on the plains of Moab before Israel crosses into Canaan. It is fundamentally about remembering: remember who God is, remember what he has done, remember the covenant, and love him with all your heart, soul, and strength (the Shema, 6:4–5). Jesus quotes Deuteronomy three times when resisting Satan in the wilderness. The book closes with the haunting death of Moses, who glimpsed the Promised Land but never entered it — a poignant picture of one who led others to the threshold of a rest he could not share.',
  },
  // ── OLD TESTAMENT: HISTORY ──────────────────────────────────
  {
    name: 'Joshua',
    abbreviation: 'Josh',
    testament: 'OT',
    section: 'History',
    author: 'Joshua; later editors',
    date: 'c. 1400–1000 BC',
    audience: 'Israel entering and settling Canaan',
    themes: ['Faithfulness', 'Conquest', 'Promise fulfilled', 'Covenant', 'Rest'],
    preface: 'Joshua is the book of promise fulfilled. After forty years in the wilderness, Israel crosses the Jordan and inherits the land God swore to Abraham centuries before. The conquest is not merely military history; it is theology in narrative form — the judgment of God against pagan nations ripened in centuries of sin, and the faithfulness of God to a promise made to a wandering nomad. Joshua\'s name is Yeshua — Jesus — and his role as the one who leads God\'s people into their inheritance is a deliberate type of the greater Joshua who leads us into our eternal rest (Hebrews 4).',
  },
  {
    name: 'Judges',
    abbreviation: 'Judg',
    testament: 'OT',
    section: 'History',
    author: 'Unknown (possibly Samuel)',
    date: 'c. 1000 BC (events c. 1380–1050 BC)',
    audience: 'Israel in the period of the judges',
    themes: ['Apostasy', 'Deliverance', 'Cycles of sin', 'Grace', 'Human weakness'],
    preface: 'Judges is one of the most brutal and honest books in the Bible. Its repeating pattern — Israel sins, God allows oppression, Israel cries out, God sends a deliverer, rest, and repeat — is a picture of the human condition without sustained covenant faithfulness. The judges themselves are flawed heroes: Gideon doubts, Samson is undone by his passions, Jephthah makes a rash vow. The book ends with the haunting refrain: "In those days there was no king in Israel. Everyone did what was right in his own eyes." It is a book that makes the reader long for a King — the right King.',
  },
  {
    name: 'Ruth',
    abbreviation: 'Ruth',
    testament: 'OT',
    section: 'History',
    author: 'Unknown (possibly Samuel)',
    date: 'c. 1000 BC (events c. 1100 BC)',
    audience: 'Israel, likely during the monarchy',
    themes: ['Loyalty', 'Redemption', 'Providence', 'Covenant love (hesed)', 'Gentile inclusion'],
    preface: 'Set in the darkest period of the judges, Ruth is a story of radiant faithfulness. A Moabite widow follows her mother-in-law back to Israel and says words that have echoed through every wedding and every funeral since: "Where you go I will go, and where you die I will die." The book is a masterpiece of covenant love (hesed) — demonstrated first by Ruth, then by Boaz, the kinsman-redeemer who rescues her. Boaz is a picture of Christ: the near kinsman who redeems what was lost and makes the foreigner his bride. Ruth enters the line of David — and of Jesus.',
  },
  {
    name: '1 Samuel',
    abbreviation: '1 Sam',
    testament: 'OT',
    section: 'History',
    author: 'Unknown (possibly Samuel, Nathan, Gad)',
    date: 'c. 931–722 BC (events c. 1100–1010 BC)',
    audience: 'Israel',
    themes: ['Kingship', 'Obedience', 'God\'s anointing', 'Human ambition', 'Covenant'],
    preface: 'First Samuel spans the transition from judges to monarchy. Samuel is the last judge and the first great prophet. Saul is Israel\'s first king — chosen for his appearance, undone by his disobedience. David is anointed as a boy, tested in the wilderness, and pursued by a jealous king. The book introduces one of Scripture\'s most important themes: God does not look on outward appearance, but on the heart (1 Samuel 16:7). The contrast between Saul\'s partial obedience and David\'s whole-hearted love for God runs through every chapter.',
  },
  {
    name: '2 Samuel',
    abbreviation: '2 Sam',
    testament: 'OT',
    section: 'History',
    author: 'Unknown',
    date: 'c. 931–722 BC (events c. 1010–970 BC)',
    audience: 'Israel',
    themes: ['The Davidic covenant', 'Sin and consequence', 'Repentance', 'God\'s grace'],
    preface: 'Second Samuel is David\'s reign — its heights and its depths. God makes an eternal covenant with David: a son of his line will reign forever (2 Samuel 7). But the same chapter that establishes the covenant is followed by David\'s catastrophic sin with Bathsheba and the murder of Uriah. The consequences cascade through his family for the rest of his life. And yet — David repents (Psalm 51). He is called "a man after God\'s own heart" not because he did not sin, but because when he did, he ran back to God. David prefigures Christ: the anointed king, the shepherd, the warrior, the covenant-keeper.',
  },
  {
    name: '1 Kings',
    abbreviation: '1 Kgs',
    testament: 'OT',
    section: 'History',
    author: 'Unknown (possibly Jeremiah or the Deuteronomistic historians)',
    date: 'c. 620–550 BC (events c. 970–850 BC)',
    audience: 'Israel and Judah',
    themes: ['Solomon\'s wisdom and failure', 'The Temple', 'Apostasy', 'The divided kingdom', 'Elijah'],
    preface: 'First Kings opens with Solomon\'s brilliant reign — the Temple built, wisdom given, nations coming to hear him — and then traces his decline as his foreign wives turn his heart to other gods. The kingdom splits after his death, and the long sad story of Israel\'s kings begins. Against this background, Elijah stands as one of Scripture\'s most dramatic figures: a prophet who calls down fire from heaven and then collapses under a juniper tree and asks to die. The story of Elijah is a story about what happens when faithfulness to God makes you a target, and what God does for people who are spent.',
  },
  {
    name: '2 Kings',
    abbreviation: '2 Kgs',
    testament: 'OT',
    section: 'History',
    author: 'Unknown (possibly Jeremiah or the Deuteronomistic historians)',
    date: 'c. 620–550 BC (events c. 850–586 BC)',
    audience: 'Israel and Judah',
    themes: ['Covenant faithfulness', 'Judgment', 'Exile', 'Elisha', 'The remnant'],
    preface: 'Second Kings is the book of exile. It traces the slow spiritual collapse of both Israel (exiled to Assyria in 722 BC) and Judah (exiled to Babylon in 586 BC). The Temple is destroyed. The Davidic line is in captivity. It seems like the end. But running through every chapter is a minority — the faithful remnant — and the persistent presence of prophets like Elisha who witness to the living God even in dark times. The book ends in exile, but the promise is not broken. The seed of David survives.',
  },
  {
    name: '1 Chronicles',
    abbreviation: '1 Chr',
    testament: 'OT',
    section: 'History',
    author: 'Ezra (traditionally)',
    date: 'c. 450–400 BC',
    audience: 'The returned exiles',
    themes: ['Davidic covenant', 'Worship', 'Temple preparations', 'Genealogy', 'Hope'],
    preface: 'Chronicles retells the story of Kings from a different angle — written for the community that had returned from exile and needed to reconnect with their identity as God\'s covenant people. Where Kings emphasizes the failure that led to exile, Chronicles emphasizes the line of David and the preparations for the Temple — anchoring the community in hope rather than shame. The extensive genealogies at the opening are not filler; they are a statement that every person in the story matters, and that God has been weaving a thread through history from the very beginning.',
  },
  {
    name: '2 Chronicles',
    abbreviation: '2 Chr',
    testament: 'OT',
    section: 'History',
    author: 'Ezra (traditionally)',
    date: 'c. 450–400 BC',
    audience: 'The returned exiles',
    themes: ['Worship', 'Covenant', 'Repentance', 'Temple', 'The remnant'],
    preface: 'Second Chronicles focuses heavily on the Temple and on kings who either maintained or abandoned true worship. The pattern is clear: when the king turns to God, the nation flourishes; when he abandons God, catastrophe follows. But the book closes not with destruction but with Cyrus\'s decree allowing the exiles to return — a note of unexpected grace that opens into Ezra and Nehemiah. The final verses of 2 Chronicles are also the opening verses of Ezra: the story is not over.',
  },
  {
    name: 'Ezra',
    abbreviation: 'Ezra',
    testament: 'OT',
    section: 'History',
    author: 'Ezra',
    date: 'c. 450–400 BC',
    audience: 'The returned exiles rebuilding the community',
    themes: ['Restoration', 'Law', 'Covenant renewal', 'Faithfulness', 'Identity'],
    preface: 'Ezra is the story of return — not just geographical, but spiritual. The exiles come back to Jerusalem and rebuild the Temple. Ezra, a scribe skilled in the Law of Moses, arrives later with a mandate to teach the people God\'s Word and to call the community back to covenant faithfulness. The book confronts the hard question of faithfulness under pressure: what does it mean to be God\'s people in a world that has moved on without you? Ezra\'s response to the people\'s sin is not anger but broken-hearted intercession — one of the great models of pastoral prayer in Scripture.',
  },
  {
    name: 'Nehemiah',
    abbreviation: 'Neh',
    testament: 'OT',
    section: 'History',
    author: 'Nehemiah',
    date: 'c. 445–400 BC',
    audience: 'The returned exiles in Jerusalem',
    themes: ['Leadership', 'Rebuilding', 'Prayer', 'Opposition', 'Community'],
    preface: 'Nehemiah is a book about building — walls and community — against opposition. Nehemiah is a practical leader: he prays, he plans, and he acts. When enemies mock and threaten, he prays (2:4) and posts guards (4:9). The rebuilt walls of Jerusalem are not just infrastructure; they are a declaration that the community of God\'s people has a future. The book climaxes with a great assembly where Ezra reads the Law and the people weep and rejoice as they hear it. The Word of God has the power to rebuild what sin has demolished.',
  },
  {
    name: 'Esther',
    abbreviation: 'Esth',
    testament: 'OT',
    section: 'History',
    author: 'Unknown',
    date: 'c. 460–350 BC',
    audience: 'Jews in the Persian diaspora',
    themes: ['Providence', 'Courage', 'Identity', 'Deliverance', 'Hidden sovereignty'],
    preface: 'Esther never mentions God — and that absence is the point. The book is about divine providence operating invisibly through ordinary human events: a beauty contest, a bureaucratic slight, an overheard conspiracy. Mordecai\'s words to Esther are among the most famous in Scripture: "Who knows whether you have not come to the kingdom for such a time as this?" Esther must choose between safety and faithfulness. She chooses faithfulness, approaching the king unsummoned at the risk of her life, and the Jewish people are saved. God is never named but is everywhere present.',
  },
  // ── OLD TESTAMENT: POETRY / WISDOM ─────────────────────────
  {
    name: 'Job',
    abbreviation: 'Job',
    testament: 'OT',
    section: 'Poetry & Wisdom',
    author: 'Unknown (one of the oldest texts in the Bible)',
    date: 'Unknown; possibly c. 2000–1500 BC in composition',
    audience: 'Anyone who has suffered',
    themes: ['Suffering', 'Theodicy', 'The sovereignty of God', 'Faithful lament', 'Encounter with God'],
    preface: 'Job refuses easy answers. A blameless man loses everything — children, wealth, health — and demands an audience with God. His friends offer tidy theological explanations. God\'s answer, when it comes, is not an explanation but a question: "Where were you when I laid the foundation of the earth?" The book does not explain suffering. It insists that suffering does not mean God is absent or unjust, and that the right response to suffering is honest speech directed at God — not silence, not accusation, but raw prayer. Job sees God face to face and is restored — not as a reward for patience, but because he spoke what was right (42:7).',
  },
  {
    name: 'Psalms',
    abbreviation: 'Ps',
    testament: 'OT',
    section: 'Poetry & Wisdom',
    author: 'David (primarily), Asaph, Sons of Korah, Solomon, Moses, others',
    date: 'c. 1400–400 BC (compiled over centuries)',
    audience: 'Israel in worship; the whole church',
    themes: ['Prayer', 'Praise', 'Lament', 'Trust', 'God\'s character', 'Messiah'],
    preface: 'The Psalms are the prayer book and hymnal of both Israel and the church. They give the people of God language for every human experience — soaring praise, utter desolation, burning anger, quiet trust. Jesus quoted the Psalms more than any other Old Testament book, and many Psalms (22, 69, 110, 118) are direct prophecies of his life, death, and resurrection. The Psalms teach us that honest prayer — including lament, complaint, and confusion — is not faithlessness. It is intimacy. God welcomes every cry.',
  },
  {
    name: 'Proverbs',
    abbreviation: 'Prov',
    testament: 'OT',
    section: 'Poetry & Wisdom',
    author: 'Solomon (primarily), Agur, King Lemuel',
    date: 'c. 970–700 BC',
    audience: 'Young people; the whole community of Israel',
    themes: ['Wisdom', 'Fear of God', 'Practical righteousness', 'Speech', 'Character'],
    preface: 'Proverbs is practical theology for everyday life. Its opening declaration — "The fear of the LORD is the beginning of wisdom" — establishes the foundation: wisdom is not primarily intellectual but relational. To know God rightly is to begin seeing the world rightly. The book addresses money, marriage, work, speech, friendship, and ambition with a directness that feels remarkably contemporary. The personification of Wisdom as a woman calling in the streets is one of the Old Testament\'s most suggestive images of Christ, who became for us "wisdom from God" (1 Corinthians 1:30).',
  },
  {
    name: 'Ecclesiastes',
    abbreviation: 'Eccl',
    testament: 'OT',
    section: 'Poetry & Wisdom',
    author: 'Qohelet ("the Preacher"); traditionally Solomon',
    date: 'c. 940–200 BC (disputed)',
    audience: 'Anyone questioning the meaning of life',
    themes: ['Vanity', 'Mortality', 'Joy', 'The limits of wisdom', 'Fear of God', 'Eternity'],
    preface: 'Ecclesiastes is the Bible\'s most startling book — a sustained meditation on the futility of life "under the sun." The Preacher has tried everything: wisdom, pleasure, work, wealth, achievement. And he finds that without reference to God, it is all "vanity" — breath, vapor, nothing that holds. Yet the book is not nihilistic. Its conclusion is deeply sane: fear God, keep his commandments. There is an eternity set in human hearts (3:11), and a judgment coming (12:14). Ecclesiastes is the Bible\'s invitation to every person who has tasted the emptiness of life without God — and wondered why it was empty.',
  },
  {
    name: 'Song of Solomon',
    abbreviation: 'Song',
    testament: 'OT',
    section: 'Poetry & Wisdom',
    author: 'Solomon',
    date: 'c. 970–930 BC',
    audience: 'Israel; married couples; the whole church',
    themes: ['Human love', 'Marriage', 'Desire', 'Beauty', 'God\'s love for his people'],
    preface: 'The Song of Solomon is the Bible\'s celebration of human love — erotic, embodied, exuberant. Its inclusion in the canon says something important: physical love between a husband and wife is good, created by God, and worthy of poetry. The rabbis who debated its canonicity concluded it was holy because it is also an allegory of God\'s love for Israel — and the church has read it as an image of Christ\'s love for his bride. Both readings are appropriate. The God who created human love uses it as the best available metaphor for his own passionate, pursuing love for his people.',
  },
  // ── OLD TESTAMENT: MAJOR PROPHETS ───────────────────────────
  {
    name: 'Isaiah',
    abbreviation: 'Isa',
    testament: 'OT',
    section: 'Major Prophets',
    author: 'Isaiah son of Amoz',
    date: 'c. 740–700 BC',
    audience: 'Judah under the threat of Assyria',
    themes: ['Holiness of God', 'Judgment', 'The Servant', 'Restoration', 'New creation', 'Comfort'],
    preface: 'Isaiah is sometimes called "the fifth Gospel" because its prophetic vision of the coming Servant of the LORD is so precise that New Testament writers quote it constantly to explain what Jesus did. The vision of chapter 6 (God on his throne, Isaiah undone by holiness), the Immanuel prophecy of chapter 7, the suffering Servant of chapters 52–53 ("he was wounded for our transgressions"), and the new creation of chapters 65–66 — all find their fulfilment in Christ. Isaiah preached for forty years in a court that mostly refused to listen. He was, according to tradition, sawn in two under King Manasseh. The book that bears his name is one of the greatest literary and theological achievements in history.',
  },
  {
    name: 'Jeremiah',
    abbreviation: 'Jer',
    testament: 'OT',
    section: 'Major Prophets',
    author: 'Jeremiah son of Hilkiah; Baruch his scribe',
    date: 'c. 627–585 BC',
    audience: 'Judah in the years before and after the Babylonian exile',
    themes: ['Judgment', 'Lament', 'The new covenant', 'False religion', 'Faithfulness under pressure'],
    preface: 'Jeremiah is called the "weeping prophet" — not as a pejorative but as a description of someone who loved deeply the people he was called to warn. He prophesied for forty years and was ignored, mocked, imprisoned, and thrown into a cistern. He never saw revival. He watched Jerusalem fall. And yet his great legacy is the promise of the new covenant in chapter 31: "I will put my law within them, and I will write it on their hearts… they shall all know me." Jesus took the cup at the Last Supper and called it "the new covenant in my blood" — Jeremiah\'s promise, finally fulfilled.',
  },
  {
    name: 'Lamentations',
    abbreviation: 'Lam',
    testament: 'OT',
    section: 'Major Prophets',
    author: 'Jeremiah (traditionally)',
    date: 'c. 586 BC',
    audience: 'The survivors of Jerusalem\'s destruction',
    themes: ['Grief', 'Judgment', 'Hope amid desolation', 'God\'s faithfulness', 'Communal lament'],
    preface: 'Lamentations is five poems written in the ruins. Jerusalem has fallen. The Temple is destroyed. The covenant people are in exile or dead. Jeremiah (or another eyewitness) sits in the rubble and weeps — in carefully structured Hebrew poetry, which is itself an act of defiant faith: if you can still make art in this darkness, hope is not entirely gone. The center of the book (3:22–23) is one of the most quoted passages in Scripture: "The steadfast love of the LORD never ceases; his mercies never come to an end; they are new every morning." This is not wishful thinking — it is faith clinging to what is true in the face of evidence that seems to contradict it.',
  },
  {
    name: 'Ezekiel',
    abbreviation: 'Ezek',
    testament: 'OT',
    section: 'Major Prophets',
    author: 'Ezekiel son of Buzi',
    date: 'c. 593–571 BC',
    audience: 'The Jewish exiles in Babylon',
    themes: ['The glory of God', 'Judgment', 'Restoration', 'The new heart', 'New Temple', 'Resurrection'],
    preface: 'Ezekiel is the most visionary of the prophets — his opening vision of the four living creatures and the wheel within a wheel became the basis for much of the imagery in Revelation. He ministers to the exiles in Babylon, assuring them that God\'s glory has not been abandoned with the destroyed Temple. His great promise is the new heart: "I will remove the heart of stone from your flesh and give you a heart of flesh. And I will put my Spirit within you" (36:26–27). The valley of dry bones (chapter 37) is the Bible\'s most powerful image of resurrection — from death to life by the breath of God.',
  },
  {
    name: 'Daniel',
    abbreviation: 'Dan',
    testament: 'OT',
    section: 'Major Prophets',
    author: 'Daniel',
    date: 'c. 605–536 BC',
    audience: 'Jews living under pagan empire',
    themes: ['Faithfulness under pressure', 'God\'s sovereignty over nations', 'Apocalypse', 'The Son of Man'],
    preface: 'Daniel is a book of two halves: stories of faithfulness (lions\' den, fiery furnace) and visions of cosmic history. The common theme is that God reigns over every earthly empire, no matter how powerful it appears. Daniel and his friends refuse to compromise their worship, and God vindicates them. The visions of chapters 7–12 use apocalyptic imagery to assure the faithful that world history is moving toward a fixed point — the arrival of "one like a son of man" who receives an eternal kingdom. Jesus applies this title to himself more than any other and uses it in his own explanation of his return.',
  },
  // ── OLD TESTAMENT: MINOR PROPHETS ───────────────────────────
  {
    name: 'Hosea',
    abbreviation: 'Hos',
    testament: 'OT',
    section: 'Minor Prophets',
    author: 'Hosea',
    date: 'c. 750–722 BC',
    audience: 'The northern kingdom of Israel',
    themes: ['God\'s covenant love', 'Spiritual adultery', 'Repentance', 'Restoration'],
    preface: 'Hosea is commanded to do the most painful and extraordinary thing asked of any prophet: to marry an unfaithful wife as a living parable of Israel\'s unfaithfulness to God. His marriage to Gomer — and his relentless pursuit of her even after her betrayal — is one of the most shattering images of divine love in Scripture. God is not a deity who walks away when Israel breaks faith. He pursues. He disciplines. He redeems. Matthew quotes Hosea 11:1 ("out of Egypt I called my son") to describe the holy family\'s return from Egypt — Jesus, the true Israel, recapitulates Israel\'s story and succeeds where they failed.',
  },
  {
    name: 'Joel',
    abbreviation: 'Joel',
    testament: 'OT',
    section: 'Minor Prophets',
    author: 'Joel son of Pethuel',
    date: 'c. 835–400 BC (disputed)',
    audience: 'Judah',
    themes: ['The Day of the LORD', 'Repentance', 'The Spirit poured out', 'Restoration'],
    preface: 'Joel interprets a devastating locust plague as a foretaste of "the Day of the LORD" — the coming day of divine judgment and renewal. His call to repentance is one of the most urgent in Scripture: "Rend your hearts, not your garments" (2:13). But the heart of Joel is the promise of Pentecost: "I will pour out my Spirit on all flesh; your sons and daughters shall prophesy" (2:28). Peter quotes this prophecy in Acts 2 as the explanation for what was happening in Jerusalem on the Day of Pentecost. Joel\'s vision of the Spirit available to all — not just prophets, kings, and priests — was fulfilled when the Spirit fell.',
  },
  {
    name: 'Amos',
    abbreviation: 'Amos',
    testament: 'OT',
    section: 'Minor Prophets',
    author: 'Amos of Tekoa',
    date: 'c. 760–750 BC',
    audience: 'The prosperous northern kingdom of Israel',
    themes: ['Social justice', 'Judgment on religious hypocrisy', 'The poor', 'Covenant faithfulness'],
    preface: 'Amos is a shepherd from the south called to prophesy against the prosperous north — a man of no credentials, no priestly family, no prophetic school. And his message is devastating: you are wealthy and religious and utterly rotten. You trample the poor and offer sacrifices at the same time. God says: "I hate, I despise your feasts… but let justice roll down like waters, and righteousness like an ever-flowing stream" (5:21–24). Amos is the prophet for every age in which religious activity coexists with economic injustice and callousness toward the poor.',
  },
  {
    name: 'Obadiah',
    abbreviation: 'Obad',
    testament: 'OT',
    section: 'Minor Prophets',
    author: 'Obadiah',
    date: 'c. 850–586 BC (disputed)',
    audience: 'Judah, regarding Edom',
    themes: ['Divine judgment', 'Pride', 'The nations', 'God\'s justice'],
    preface: 'The shortest book in the Old Testament (21 verses) is a single oracles of judgment against Edom — the nation descended from Esau, Jacob\'s brother. Edom had gloated when Jerusalem fell and handed over Judean refugees to their enemies. The core message is simple: pride goes before destruction, and those who stand aside when their brothers are persecuted will answer for it. The book concludes with the vision of a day when "the kingdom shall be the LORD\'s" — justice will come, and it will be final.',
  },
  {
    name: 'Jonah',
    abbreviation: 'Jon',
    testament: 'OT',
    section: 'Minor Prophets',
    author: 'Unknown (Jonah himself, or a later author)',
    date: 'c. 780–400 BC',
    audience: 'Israel',
    themes: ['The grace of God toward outsiders', 'Prophetic calling', 'Repentance', 'God\'s compassion'],
    preface: 'Jonah is one of the strangest and funniest books in Scripture — a prophet who flees from God, is swallowed by a fish, preaches the most successful revival in history to the people he hates most (Assyrian Nineveh), and then sulks about it. The book is not really about a fish. It is about the scandal of divine grace extended to the wrong people — the enemies, the Gentiles, the nations Israel despises. Jesus uses Jonah as a sign of his own death and resurrection (Matthew 12:40), and as an example that Gentiles respond to God\'s word even when God\'s own people won\'t.',
  },
  {
    name: 'Micah',
    abbreviation: 'Mic',
    testament: 'OT',
    section: 'Minor Prophets',
    author: 'Micah of Moresheth',
    date: 'c. 735–700 BC',
    audience: 'Judah and Israel',
    themes: ['Justice', 'Judgment on corrupt leaders', 'The coming King', 'Covenant faithfulness'],
    preface: 'Micah speaks to corrupt leaders, false prophets, and an unjust economic system with one of the Bible\'s sharpest summary statements: "He has told you, O man, what is good; and what does the LORD require of you but to do justice, and to love kindness, and to walk humbly with your God?" (6:8). He also prophesies the birthplace of the Messiah: "But you, O Bethlehem Ephrathah… from you shall come forth for me one who is to be ruler in Israel, whose coming forth is from of old, from ancient days" (5:2). Matthew quotes this at Jesus\' birth.',
  },
  {
    name: 'Nahum',
    abbreviation: 'Nah',
    testament: 'OT',
    section: 'Minor Prophets',
    author: 'Nahum of Elkosh',
    date: 'c. 663–612 BC',
    audience: 'Judah, regarding Nineveh',
    themes: ['God\'s justice', 'The fall of oppressive power', 'Comfort for the oppressed'],
    preface: 'Where Jonah saw Nineveh repent, Nahum sees a Nineveh that has returned to violence. The Assyrian empire was the superpower of the ancient Near East — brutal, efficient, terrifying. Nahum\'s prophecy of its destruction was, humanly speaking, unthinkable. But it came true in 612 BC when Nineveh fell. The book opens with a portrait of God that is simultaneously terrifying and comforting: "The LORD is slow to anger and great in power, and the LORD will by no means clear the guilty" (1:3). His patience is real; so is his justice.',
  },
  {
    name: 'Habakkuk',
    abbreviation: 'Hab',
    testament: 'OT',
    section: 'Minor Prophets',
    author: 'Habakkuk',
    date: 'c. 612–589 BC',
    audience: 'Judah',
    themes: ['Theodicy', 'Faith under darkness', 'God\'s sovereignty', 'Righteous living'],
    preface: 'Habakkuk is remarkable for its form: it is a dialogue with God. The prophet complains that God is not answering his prayers about injustice in Judah. God answers: he will use Babylon to judge. Habakkuk complains again: how can you use a more wicked nation to punish a less wicked one? God answers again. The book ends with one of the great declarations of faith in all of Scripture: "Though the fig tree should not blossom, nor fruit be on the vines… yet I will rejoice in the LORD; I will take joy in the God of my salvation" (3:17–18). And the single most important line: "the righteous shall live by faith" (2:4) — quoted three times in the New Testament.',
  },
  {
    name: 'Zephaniah',
    abbreviation: 'Zeph',
    testament: 'OT',
    section: 'Minor Prophets',
    author: 'Zephaniah son of Cushi',
    date: 'c. 640–609 BC',
    audience: 'Judah under King Josiah',
    themes: ['The Day of the LORD', 'Judgment', 'The remnant', 'God\'s rejoicing over his people'],
    preface: 'Zephaniah opens with sweeping judgment — "I will utterly sweep away everything from the face of the earth" — and ends with one of the most beautiful verses in the Old Testament: "The LORD your God is in your midst, a mighty one who will save; he will rejoice over you with gladness; he will quiet you by his love; he will exult over you with loud singing" (3:17). The same God who judges is the God who sings over his restored people. Zephaniah holds both realities without flinching.',
  },
  {
    name: 'Haggai',
    abbreviation: 'Hag',
    testament: 'OT',
    section: 'Minor Prophets',
    author: 'Haggai',
    date: 'c. 520 BC',
    audience: 'The returned exiles in Jerusalem',
    themes: ['Priorities', 'The Temple', 'God\'s presence', 'Obedience'],
    preface: 'Haggai is one of the most practical prophets. The returned exiles are building their own houses while the Temple sits unfinished. Haggai asks: "Is it a time for you yourselves to dwell in your paneled houses, while this house lies in ruins?" (1:4). The message is not primarily about a building — it is about whether God is at the center of the community\'s life, or on the margins. The people respond, and within three weeks the work restarts. The book is a short but powerful lesson about misplaced priorities.',
  },
  {
    name: 'Zechariah',
    abbreviation: 'Zech',
    testament: 'OT',
    section: 'Minor Prophets',
    author: 'Zechariah son of Berechiah',
    date: 'c. 520–480 BC',
    audience: 'The returned exiles',
    themes: ['Messianic prophecy', 'Restoration', 'The Spirit', 'Visions', 'The coming King'],
    preface: 'Zechariah is the most quoted Old Testament prophet in the Passion narratives of the Gospels. His prophecies include: the King coming on a donkey (9:9, fulfilled in the Triumphal Entry), thirty pieces of silver (11:12–13), the one whom they have pierced (12:10), and the shepherd struck and the sheep scattered (13:7). The visions of the first eight chapters are elaborate and strange — Joshua the high priest clothed in filthy rags and then clean garments is a picture of justification. Zechariah gives the post-exilic community a vision of a coming age in which God himself will dwell among his people.',
  },
  {
    name: 'Malachi',
    abbreviation: 'Mal',
    testament: 'OT',
    section: 'Minor Prophets',
    author: 'Malachi',
    date: 'c. 450–400 BC',
    audience: 'The returned exiles in Judah',
    themes: ['Covenant faithfulness', 'Worship', 'Tithing', 'The coming messenger', 'Elijah'],
    preface: 'Malachi is the last word of the Old Testament — and it ends with a promise and a warning: Elijah will come before the great Day of the LORD (4:5). Four hundred years of silence follow. Then, in the wilderness, a voice begins to cry: "Prepare the way of the LORD." John the Baptist is the Elijah who was to come (Matthew 11:14). Malachi is a book about a community going through the motions — offering blind and lame animals, withholding tithes, and wondering why God seems distant. The answer is searching: "Return to me, and I will return to you" (3:7). The whole Old Testament ends on this note of expectation.',
  },
  // ── NEW TESTAMENT: GOSPELS ──────────────────────────────────
  {
    name: 'Matthew',
    abbreviation: 'Matt',
    testament: 'NT',
    section: 'Gospels',
    author: 'Matthew (Levi), the tax collector and apostle',
    date: 'c. 50–70 AD',
    audience: 'Jewish Christians; audiences familiar with the Old Testament',
    themes: ['Jesus as the fulfillment of Israel\'s story', 'The Kingdom of heaven', 'Discipleship', 'The Great Commission'],
    preface: 'Matthew writes primarily for a Jewish audience and is obsessed with demonstrating that Jesus is the fulfillment of every promise in the Old Testament. His opening genealogy connects Jesus to Abraham and David. His five great discourses (the Sermon on the Mount, the Mission Discourse, the Parables of the Kingdom, the Community Discourse, and the Olivet Discourse) echo the five books of Moses — Jesus is the new Moses, the new lawgiver, giving a new and better Torah. Matthew closes with the Great Commission: "Go therefore and make disciples of all nations." The Jewish Messiah is for the whole world.',
  },
  {
    name: 'Mark',
    abbreviation: 'Mark',
    testament: 'NT',
    section: 'Gospels',
    author: 'John Mark, companion of Peter',
    date: 'c. 55–70 AD',
    audience: 'Roman Gentile Christians',
    themes: ['The Servant King', 'Action and authority', 'Suffering', 'Discipleship', 'The cross'],
    preface: 'Mark is the shortest and most urgent Gospel — the word "immediately" appears over 40 times. Written for a Roman audience, it emphasizes what Jesus did more than what he said. Mark presents Jesus as the Servant who came "not to be served but to serve, and to give his life as a ransom for many" (10:45). The Gospel moves with breathless speed toward the cross, which occupies an enormous proportion of the narrative. Mark\'s Gospel is thought to be based on Peter\'s preaching and carries the vividness of an eyewitness throughout.',
  },
  {
    name: 'Luke',
    abbreviation: 'Luke',
    testament: 'NT',
    section: 'Gospels',
    author: 'Luke, the physician and companion of Paul',
    date: 'c. 60–80 AD',
    audience: 'Gentile Christians; a Greco-Roman audience',
    themes: ['The universal reach of the gospel', 'Women and the marginalized', 'Prayer', 'The Holy Spirit', 'The poor'],
    preface: 'Luke is the most literary of the Gospels — a careful, ordered account written by a trained doctor who conducted extensive research (1:1–4). Luke gives more attention to women, the poor, the outcast, and the Gentile than any other Gospel. He alone records the parables of the Good Samaritan, the Prodigal Son, and the Pharisee and Tax Collector. His Jesus prays constantly, weeps over Jerusalem, and welcomes sinners. Luke\'s Gospel is the first volume of a two-part work; Acts is its sequel. Together they trace the movement of the gospel from a manger in Bethlehem to the center of the Roman Empire.',
  },
  {
    name: 'John',
    abbreviation: 'John',
    testament: 'NT',
    section: 'Gospels',
    author: 'John son of Zebedee, the apostle',
    date: 'c. 80–100 AD',
    audience: 'The whole church; specifically those confronting early proto-Gnostic heresies',
    themes: ['The deity of Christ', 'Eternal life', 'Light and darkness', 'Love', 'Belief'],
    preface: 'John\'s Gospel begins where Genesis begins: "In the beginning." But where Genesis begins with creation, John begins with the eternal Word through whom creation was made — and that Word became flesh and dwelt among us. John writes to show that Jesus is fully God (1:1) and fully human (1:14), and that in him is eternal life for all who believe (3:16). The seven great "I AM" statements (the Bread of Life, the Light of the World, the Good Shepherd, etc.) are deliberate echoes of God\'s name in Exodus 3. John\'s Gospel is the most theological and the most intimate — the eagle sees what the others do not.',
  },
  // ── NEW TESTAMENT: ACTS ─────────────────────────────────────
  {
    name: 'Acts',
    abbreviation: 'Acts',
    testament: 'NT',
    section: 'Acts',
    author: 'Luke, the physician',
    date: 'c. 62–80 AD',
    audience: 'Gentile Christians; Theophilus',
    themes: ['The Holy Spirit', 'The church', 'Mission', 'The gospel to the nations', 'Witness'],
    preface: 'Acts is the story of what happened after the resurrection — and the answer is: everything. The Spirit falls, 3,000 are converted in a day, the church forms, spreads to Samaria, then to the Gentiles through Peter, then across the Mediterranean world through Paul. Luke traces the gospel\'s movement from Jerusalem to Rome in three decades. Acts is not merely historical; it is paradigmatic. The church in every age is called to the same mission by the same Spirit. The book ends with Paul preaching openly in Rome, the center of the empire — "with all boldness and without hindrance" (28:31). The story is still continuing.',
  },
  // ── NEW TESTAMENT: PAUL'S LETTERS ──────────────────────────
  {
    name: 'Romans',
    abbreviation: 'Rom',
    testament: 'NT',
    section: "Paul's Letters",
    author: 'Paul the Apostle',
    date: 'c. 57 AD',
    audience: 'The church in Rome',
    themes: ['Justification by faith', 'Sin and grace', 'The law', 'Israel and the Gentiles', 'The Christian life'],
    preface: 'Romans is Paul\'s most systematic presentation of the gospel — written to a church he had never visited, as a theological introduction before his planned visit. It begins with the diagnosis: all have sinned (1:18–3:20). It presents the cure: justification by faith through the blood of Christ (3:21–5:21). It traces the implications: union with Christ, freedom from sin, the Spirit\'s work, Israel\'s place in God\'s plan. And it ends with the application: present your bodies as living sacrifices (12:1). Augustine was converted reading Romans 13. Luther was converted reading Romans 1:17. It is arguably the most important letter ever written.',
  },
  {
    name: '1 Corinthians',
    abbreviation: '1 Cor',
    testament: 'NT',
    section: "Paul's Letters",
    author: 'Paul the Apostle',
    date: 'c. 53–54 AD',
    audience: 'The church in Corinth',
    themes: ['Unity', 'The cross and human wisdom', 'Spiritual gifts', 'The resurrection', 'Love', 'The Lord\'s Supper'],
    preface: 'First Corinthians is Paul writing to a charismatic, talented, deeply fractured church. They are divided over leaders, suing each other in court, tolerating sexual immorality, misusing spiritual gifts, and turning the Lord\'s Supper into a class-divided meal. Paul\'s response is not to dismiss the gifts — it is to anchor everything in the cross (1:18–2:5) and to teach that love is the measure of everything (chapter 13). The famous "love chapter" was not written for weddings. It was written as a rebuke of a church confusing gifts for maturity. Chapter 15 is the most important treatment of the resurrection in the New Testament.',
  },
  {
    name: '2 Corinthians',
    abbreviation: '2 Cor',
    testament: 'NT',
    section: "Paul's Letters",
    author: 'Paul the Apostle',
    date: 'c. 55–56 AD',
    audience: 'The church in Corinth',
    themes: ['Weakness and power', 'Suffering', 'Authentic ministry', 'Reconciliation', 'Generosity'],
    preface: 'Second Corinthians is Paul\'s most personal letter — written out of pain, in defense of his ministry against false apostles who were impressive in appearance but hollow in substance. Paul\'s defense of himself is counter-intuitive: he boasts in weakness, suffering, and humiliation. "When I am weak, then I am strong" (12:10). The theology of the cross shapes Paul\'s entire understanding of ministry: the power of God is displayed not through impressive résumés but through cracked pots. The final four chapters (the "foolish boasting") are some of the most rhetorically powerful writing in the New Testament.',
  },
  {
    name: 'Galatians',
    abbreviation: 'Gal',
    testament: 'NT',
    section: "Paul's Letters",
    author: 'Paul the Apostle',
    date: 'c. 48–55 AD',
    audience: 'The churches of Galatia (modern Turkey)',
    themes: ['Justification by faith alone', 'Freedom from the law', 'The false gospel of works', 'Life in the Spirit'],
    preface: 'Paul writes Galatians in a fury — no greeting, no thanksgiving, just an anathema: if anyone preaches a different gospel, let him be accursed. Jewish-Christian teachers have been telling the Galatian believers that faith in Christ is not enough; they must also be circumcised and keep the Torah to be fully saved. Paul\'s response is one of the most important arguments in history: the gospel is justification by faith alone, and to add anything to it is to lose it. Luther\'s discovery of Galatians broke the Reformation open. "For freedom Christ has set us free," Paul writes — and that freedom is not license but sonship: we are not slaves but children, heirs, those led by the Spirit.',
  },
  {
    name: 'Ephesians',
    abbreviation: 'Eph',
    testament: 'NT',
    section: "Paul's Letters",
    author: 'Paul the Apostle',
    date: 'c. 60–62 AD',
    audience: 'The church in Ephesus (possibly a circular letter)',
    themes: ['The church as God\'s new humanity', 'Grace', 'Spiritual warfare', 'Marriage and family', 'Unity'],
    preface: 'Ephesians is the cathedral of Paul\'s letters — a soaring, breathtaking vision of what God has done in Christ and what he is building in the church. The first three chapters are pure theology: chosen before the foundation of the world, adopted as sons, saved by grace through faith, made one new humanity from Jew and Gentile, the church as the fullness of Christ. The last three chapters are the application: walk worthy of the calling, be filled with the Spirit, put on the whole armor of God. The letter closes with the image of a soldier armed for battle — because what God is doing in the church is set against very real spiritual opposition.',
  },
  {
    name: 'Philippians',
    abbreviation: 'Phil',
    testament: 'NT',
    section: "Paul's Letters",
    author: 'Paul the Apostle',
    date: 'c. 61–62 AD',
    audience: 'The church in Philippi',
    themes: ['Joy', 'The humility of Christ', 'Contentment', 'Partnership in the gospel', 'The peace of God'],
    preface: 'Philippians is Paul\'s most joyful letter — written from prison, to a church he loves, about a joy that has no external cause. The word "rejoice" appears more than any other letter. The great Christological hymn of 2:5–11 — the descent of Christ from divine glory to a cross, and his subsequent exaltation above every name — is framed as the pattern of Christian living: have this mind among yourselves. Joy in Paul is not an emotion; it is a settled orientation of the soul toward the goodness of God, available even in prison, even in the face of death.',
  },
  {
    name: 'Colossians',
    abbreviation: 'Col',
    testament: 'NT',
    section: "Paul's Letters",
    author: 'Paul the Apostle',
    date: 'c. 60–62 AD',
    audience: 'The church in Colossae',
    themes: ['The supremacy of Christ', 'False teaching', 'Christ as the fullness of God', 'New life in Christ'],
    preface: 'Written to counter a "philosophy" that was adding elements to the gospel — angel worship, dietary rules, mystical experiences — Colossians insists that Christ is sufficient. The great hymn of 1:15–20 is one of the highest Christological passages in the New Testament: "He is the image of the invisible God, the firstborn of all creation… in him all the fullness of God was pleased to dwell." Paul\'s point is precise: if Christ is who he is, there is nothing to add. You are complete in him. Let no one disqualify you.',
  },
  {
    name: '1 Thessalonians',
    abbreviation: '1 Thess',
    testament: 'NT',
    section: "Paul's Letters",
    author: 'Paul the Apostle',
    date: 'c. 50–51 AD (the earliest of Paul\'s letters)',
    audience: 'The church in Thessalonica',
    themes: ['The return of Christ', 'Christian living', 'Holiness', 'Grief and hope', 'Encouragement'],
    preface: 'First Thessalonians may be the earliest document in the New Testament. Paul writes to a young church he had to leave suddenly under persecution, and he is anxious about them — are they still standing? Timothy reports that they are, and Paul\'s relief and joy overflow into the letter. The great theme is the return of Christ: believers who have died are not lost; they will rise at his coming. The famous passage about the "rapture" in 4:13–18 was written as comfort to grieving people, not as a code to decode current events. "Therefore encourage one another with these words" (4:18) — that is the point.',
  },
  {
    name: '2 Thessalonians',
    abbreviation: '2 Thess',
    testament: 'NT',
    section: "Paul's Letters",
    author: 'Paul the Apostle',
    date: 'c. 51–52 AD',
    audience: 'The church in Thessalonica',
    themes: ['The Day of the Lord', 'The man of lawlessness', 'Perseverance', 'Work and idleness'],
    preface: 'Paul writes a second time to correct a misunderstanding — some in Thessalonica believe the Day of the Lord has already come, and are using this belief as an excuse to stop working. Paul gives additional teaching about the sequence of events before Christ\'s return (the rebellion, the man of lawlessness) and then turns practical: "If anyone is not willing to work, let him not eat." Theological confusion about the end times is not a reason for idleness. Until Christ returns, faithful work is a form of discipleship.',
  },
  {
    name: '1 Timothy',
    abbreviation: '1 Tim',
    testament: 'NT',
    section: "Paul's Letters",
    author: 'Paul the Apostle',
    date: 'c. 62–64 AD',
    audience: 'Timothy, Paul\'s young co-worker in Ephesus',
    themes: ['Church order', 'False teaching', 'Leadership', 'Prayer', 'Godliness'],
    preface: 'Paul writes to his young protégé Timothy, left in Ephesus to deal with false teachers and establish proper church order. The letter is intensely practical: qualifications for elders and deacons, instructions for prayer, warnings about the love of money, exhortations about how different age groups should be treated. Its famous declaration — "There is one God, and there is one mediator between God and men, the man Christ Jesus" (2:5) — anchors everything in the uniqueness of the gospel. Timothy is young and apparently timid; Paul exhorts him: "Let no one despise you for your youth, but set the believers an example in speech, in conduct, in love, in faith, in purity" (4:12).',
  },
  {
    name: '2 Timothy',
    abbreviation: '2 Tim',
    testament: 'NT',
    section: "Paul's Letters",
    author: 'Paul the Apostle',
    date: 'c. 66–68 AD (Paul\'s final letter before his execution)',
    audience: 'Timothy',
    themes: ['Faithfulness under pressure', 'The Word of God', 'Endurance', 'Succession', 'Paul\'s legacy'],
    preface: 'Second Timothy is Paul\'s final letter, written from prison in Rome as he awaits execution. It is the most personal thing he wrote — a dying man writing to his son in the faith. "I have fought the good fight, I have finished the race, I have kept the faith" (4:7). He urges Timothy to guard the gospel, to endure hardship as a good soldier, and above all to "preach the word; be ready in season and out of season" (4:2). The great text on Scripture\'s inspiration and sufficiency (3:16–17) is the foundation for everything else: a church anchored to the Word can stand when everything else shifts.',
  },
  {
    name: 'Titus',
    abbreviation: 'Titus',
    testament: 'NT',
    section: "Paul's Letters",
    author: 'Paul the Apostle',
    date: 'c. 63–65 AD',
    audience: 'Titus, Paul\'s co-worker on Crete',
    themes: ['Church leadership', 'Sound doctrine', 'Godly living', 'Grace and good works'],
    preface: 'Like 1 Timothy, Titus addresses church order — Titus is to appoint elders in every town in Crete, silence false teachers, and exhort different groups (older men, older women, younger men, slaves) toward godly living. The theological spine of the letter is the relationship between grace and good works: "For the grace of God has appeared, bringing salvation for all people, training us to renounce ungodliness and worldly passions, and to live self-controlled, upright, and godly lives" (2:11–12). Grace is not opposed to godliness; it produces it.',
  },
  {
    name: 'Philemon',
    abbreviation: 'Phlm',
    testament: 'NT',
    section: "Paul's Letters",
    author: 'Paul the Apostle',
    date: 'c. 60–62 AD',
    audience: 'Philemon, a Christian slave owner',
    themes: ['Reconciliation', 'Brotherhood in Christ', 'The gospel and social structures', 'Forgiveness'],
    preface: 'The shortest of Paul\'s letters — 25 verses — is one of the most socially radical. Onesimus, a runaway slave, has encountered Paul in prison and become a Christian. Paul sends him back to his master Philemon with this letter: receive him "no longer as a bondservant but better than a bondservant, as a dear brother" (v. 16). Paul does not call for the abolition of slavery in this letter. What he does is more subversive: he calls Philemon to treat his slave as a brother in Christ — which, if taken seriously, would make slavery impossible.',
  },
  // ── NEW TESTAMENT: GENERAL LETTERS ─────────────────────────
  {
    name: 'Hebrews',
    abbreviation: 'Heb',
    testament: 'NT',
    section: 'General Letters',
    author: 'Unknown (Paul, Barnabas, Apollos, and Priscilla all suggested)',
    date: 'c. 60–70 AD',
    audience: 'Jewish Christians tempted to return to Judaism',
    themes: ['The superiority of Christ', 'High priesthood', 'Faith and endurance', 'The new covenant', 'Better sacrifices'],
    preface: 'Hebrews is the great "better" book — Jesus is better than Moses, better than the angels, better than Aaron, better than the Levitical sacrifices. Written to Jewish Christians considering a return to Judaism under the pressure of persecution, the letter demonstrates that everything in the Old Testament was pointing forward to Christ and finds its fulfillment in him. The Levitical high priest entered the Holy of Holies once a year, and only with blood. Jesus entered the very presence of God with his own blood, once for all, and remains there as our eternal intercessor. The famous "Hall of Faith" in chapter 11 is followed by the great summons: run with endurance, looking to Jesus.',
  },
  {
    name: 'James',
    abbreviation: 'Jas',
    testament: 'NT',
    section: 'General Letters',
    author: 'James, the brother of Jesus',
    date: 'c. 45–62 AD (possibly the earliest New Testament letter)',
    audience: 'Jewish Christians in the diaspora',
    themes: ['Faith and works', 'Trials', 'Speech', 'Wealth and poverty', 'Wisdom', 'Prayer'],
    preface: 'James is the most practical book in the New Testament — a letter from the brother of Jesus who became the leader of the Jerusalem church. He does not write abstract theology; he writes about concrete daily life: how to handle trials, how to use the tongue, how to treat the poor. His famous statement — "faith without works is dead" (2:17) — is not a contradiction of Paul, but a different angle on the same truth: genuine faith transforms behavior. Luther famously called James "an epistle of straw," but he was wrong. James is vital evidence that the gospel produces a new way of living, not just a new set of beliefs.',
  },
  {
    name: '1 Peter',
    abbreviation: '1 Pet',
    testament: 'NT',
    section: 'General Letters',
    author: 'Peter the Apostle',
    date: 'c. 62–64 AD',
    audience: 'Christians scattered across Asia Minor, living as "sojourners and exiles"',
    themes: ['Suffering and hope', 'Holiness', 'Christian identity', 'Witness', 'The living hope'],
    preface: 'Peter writes to believers who are experiencing social marginalization and low-level persecution — they are strangers in their own culture. His response is not to tell them to fight back or to withdraw. He tells them who they are: "a chosen race, a royal priesthood, a holy nation, a people for his own possession" (2:9). Their identity is not determined by how their culture treats them. They are exiles — and exiles live by a different standard, with their eyes on a different country. The letter is saturated with the hope of resurrection and the prospect of Christ\'s return.',
  },
  {
    name: '2 Peter',
    abbreviation: '2 Pet',
    testament: 'NT',
    section: 'General Letters',
    author: 'Peter the Apostle',
    date: 'c. 64–68 AD',
    audience: 'The church broadly',
    themes: ['False teachers', 'The Word of God', 'The Day of the Lord', 'Godliness and knowledge'],
    preface: 'Second Peter, like 2 Timothy, is written near the end of Peter\'s life (he was executed under Nero, c. 64–68 AD). He focuses on false teachers who are distorting the gospel and living immorally, and on the certainty of Christ\'s return — which some are beginning to doubt. His great statement about Scripture (1:20–21) is foundational: no prophecy was produced by human will, but by men carried along by the Holy Spirit. The letter ends with a vision of the new heavens and new earth — and the exhortation to live now in light of that coming reality.',
  },
  {
    name: '1 John',
    abbreviation: '1 John',
    testament: 'NT',
    section: 'General Letters',
    author: 'John the Apostle',
    date: 'c. 85–100 AD',
    audience: 'A community of churches being divided by early Gnostic teaching',
    themes: ['Love', 'Light and darkness', 'The incarnation', 'Assurance', 'Abiding in Christ'],
    preface: 'John writes to a community that has been fractured by teachers who deny that Jesus came in the flesh (proto-Gnosticism). His response is to insist on both the reality of the incarnation and the inseparability of love and truth. The letter contains some of the most memorable sentences in the New Testament: "God is love" (4:8), "perfect love casts out fear" (4:18), "If anyone says \'I love God\' and hates his brother, he is a liar" (4:20). Assurance comes not through mystical experience but through the practical evidence of love, obedience, and genuine faith in the incarnate Christ.',
  },
  {
    name: '2 John',
    abbreviation: '2 John',
    testament: 'NT',
    section: 'General Letters',
    author: 'John the Apostle ("the elder")',
    date: 'c. 85–100 AD',
    audience: '"The elect lady and her children" — a local church',
    themes: ['Truth and love', 'False teachers', 'Hospitality with discernment'],
    preface: 'The shortest book in the New Testament (13 verses) is a personal note from the apostle John to a congregation, warning them about itinerant teachers who deny the incarnation. The letter insists that truth and love are not opposites — true love walks according to the commandments, and true hospitality does not extend to those who would destroy the faith of the community. "Watch yourselves, so that you may not lose what we have worked for" (v. 8).',
  },
  {
    name: '3 John',
    abbreviation: '3 John',
    testament: 'NT',
    section: 'General Letters',
    author: 'John the Apostle ("the elder")',
    date: 'c. 85–100 AD',
    audience: 'Gaius, a member of one of John\'s churches',
    themes: ['Hospitality', 'Church conflict', 'True and false leadership'],
    preface: 'Third John is a personal letter to an individual named Gaius, commending him for his generous hospitality to traveling missionaries and warning about a domineering church leader named Diotrephes who is refusing to receive John\'s emissaries and expelling those who do. It is a window into real conflict in the early church — power, hospitality, and truth all entangled. Demetrius is offered as a positive example: a man about whom everyone speaks well, including the truth itself.',
  },
  {
    name: 'Jude',
    abbreviation: 'Jude',
    testament: 'NT',
    section: 'General Letters',
    author: 'Jude, brother of James (and of Jesus)',
    date: 'c. 65–80 AD',
    audience: 'The church broadly',
    themes: ['Contending for the faith', 'False teachers', 'God\'s judgment', 'Perseverance'],
    preface: 'Jude wanted to write about salvation but was compelled instead to write about false teachers who had crept into the community. His letter is a concentrated defense of "the faith once for all delivered to the saints" — a phrase that establishes Christianity as having a definite content that can be handed on, guarded, and defended. The letter concludes with one of the great doxologies of the New Testament: "Now to him who is able to keep you from stumbling and to present you blameless before the presence of his glory with great joy — to the only God, our Savior, through Jesus Christ our Lord, be glory, majesty, dominion, and authority, before all time and now and forever. Amen."',
  },
  // ── NEW TESTAMENT: REVELATION ───────────────────────────────
  {
    name: 'Revelation',
    abbreviation: 'Rev',
    testament: 'NT',
    section: 'Apocalyptic',
    author: 'John the Apostle',
    date: 'c. 81–96 AD',
    audience: 'Seven churches in Asia Minor under Roman persecution',
    themes: ['The sovereignty of God', 'The lamb who was slain', 'The new creation', 'Judgment', 'Victory', 'Worship'],
    preface: 'Revelation is the most misunderstood book in the Bible — read as a coded newspaper and missed as a pastoral letter. John writes to seven real churches facing real Roman persecution under Domitian, using the symbolic, visual language of Jewish apocalyptic to say: the world is not as it appears. Behind the power of Rome is the Dragon. Behind the throne of the Lamb is the eternal God. And the Lamb wins. The great visions — the throne room of heaven, the four living creatures, the 144,000, the woman clothed with the sun, Babylon\'s fall, the new Jerusalem — are not a timeline to decode but a world to inhabit, a counter-vision to imperial propaganda. The book ends with the most beautiful promise in Scripture: "Behold, I am making all things new."',
  },
]

export const OT_SECTIONS = ['Torah', 'History', 'Poetry & Wisdom', 'Major Prophets', 'Minor Prophets']
export const NT_SECTIONS = ['Gospels', 'Acts', "Paul's Letters", 'General Letters', 'Apocalyptic']

export const BOOKS_BY_SECTION = (testament: 'OT' | 'NT') =>
  BIBLE_BOOKS.filter(b => b.testament === testament).reduce<Record<string, BibleBook[]>>((acc, book) => {
    if (!acc[book.section]) acc[book.section] = []
    acc[book.section].push(book)
    return acc
  }, {})
