export interface HardWord {
  id: string
  word: string
  what_you_may_have_heard: string
  what_it_actually_means: string
  the_greek_or_hebrew: string
  scripture: string
  scriptureText: string
  how_jesus_used_it: string
  the_grace_in_it: string
  transformation: string
}

export const HARD_WORDS: HardWord[] = [
  {
    id: 'repentance',
    word: 'Repentance',
    what_you_may_have_heard: 'You may have heard repentance preached as punishment — as though God is demanding that you feel terrible enough, long enough, to earn his favor back. You may have sat under preaching that wielded repentance as a weapon: a performance of contrition meant to satisfy a God who is perpetually disappointed. If that is the only version you have heard, it is worth knowing that it is a distortion of what Jesus actually meant.',
    what_it_actually_means: 'The Greek word is metanoia — meta (change) and noia (mind, thinking, perception). It literally means a change of mind, a turning, a reorientation of how you see and think. It is not primarily an emotion, though emotion often follows. It is not a performance of grief, though genuine sorrow over sin is real and right. It is a decisive turn — away from one direction and toward another. The direction you turn away from is your own way. The direction you turn toward is God. And the extraordinary thing is that this turn is not something you manufacture — it is something the Holy Spirit makes possible. Acts 5:31 says God "exalted" Jesus "to his right hand as ruler and Savior, to give repentance to Israel and forgiveness of sins." Repentance is a gift before it is a command.',
    the_greek_or_hebrew: 'Greek: metanoia (μετάνοια) — "change of mind, change of direction." Hebrew equivalent: shuv (שׁוּב) — "to return, to come back." Both words assume a relational frame: you have gone somewhere away from God, and you are coming back. The prodigal son "came to his senses" — the idiom in Luke 15:17 echoes the metanoia concept.',
    scripture: 'Acts 2:38 (CSB)',
    scriptureText: '"Repent and be baptized, each of you, in the name of Jesus Christ for the forgiveness of your sins, and you will receive the gift of the Holy Spirit."',
    how_jesus_used_it: 'Jesus opened his public ministry with the word: "Repent, for the kingdom of heaven has come near" (Matthew 4:17 CSB). But notice who he said it to and how: to fishermen on the shore, to tax collectors at dinner, to crowds gathered on hillsides. He did not say it to people who had already submitted to the religious establishment. He said it to people who were either locked out of it or burdened under it. His repentance call was not a door of condemnation — it was a door of entrance. "Come. Turn. The kingdom is right here." He also linked repentance directly to celebration: in Luke 15, the return of a repentant son produces a party, not a probationary period.',
    the_grace_in_it: 'Repentance is not a tax you pay to get God\'s forgiveness. It is the first movement of freedom. When you turn — genuinely, in the direction of God — you are not earning anything. You are receiving everything. The grace was already extended before you turned. The cross was raised before you repented. Repentance is your "yes" to a love that preceded you. It is the opening of a hand that has been clenched around something that was hurting you. The grace is not in the turning itself. The grace is in the One you are turning toward, who was running toward you before you took a single step.',
    transformation: 'The person who understands repentance as gift rather than punishment repents more freely, more often, and with less dread. They can look at their own sin honestly — without minimizing it or drowning in shame — because they know that the One they are confessing to is already running toward them. Repentance becomes a regular practice of return rather than a crisis event. It becomes the rhythm of the disciple\'s daily life: I drifted; I notice; I turn; I am home.',
  },
  {
    id: 'suffering',
    word: 'Suffer / Suffering',
    what_you_may_have_heard: 'If you grew up in certain church traditions, suffering was presented as either a sign of God\'s punishment (you must have done something wrong), a test you had to pass (just endure it and get on the other side), or worse, something to seek out as though pain itself is holy. The prosperity gospel goes the other direction entirely — insisting that suffering is always evidence of insufficient faith. Both distortions leave us alone with our pain: either ashamed of it or desperate to escape it.',
    what_it_actually_means: 'Scripture does not explain suffering philosophically — it accompanies it personally. The biblical response to suffering is not "here is why this happened" but "here is who is with you in it." Suffering in the New Testament is understood as the space in which several irreplaceable things are formed: endurance, character, proven faith, hope, and most significantly, intimacy with Christ. Paul says "I want to know Christ — yes, to know the power of his resurrection and participation in his sufferings, becoming like him in his death" (Philippians 3:10 NIV). Suffering is one of the primary places where we become like Jesus. Not because pain is good, but because the God who entered pain is present in ours.',
    the_greek_or_hebrew: 'Greek: pascho (πάσχω) — "to experience, to undergo, to suffer." The same word used of Christ\'s passion. When Scripture says "Christ suffered," it is the same word used when you suffer. The suffering of Jesus and our suffering share the same vocabulary — which is not coincidental. The theological point is that in his suffering he entered ours, so that in ours, he is not absent.',
    scripture: 'Romans 5:3–4 (CSB)',
    scriptureText: '"We also boast in our afflictions, because we know that affliction produces endurance, endurance produces proven character, and proven character produces hope."',
    how_jesus_used_it: 'Jesus did not promise his disciples escape from suffering — he promised his presence in it: "In this world you will have trouble. But take heart! I have overcome the world" (John 16:33 NIV). He also modeled a different posture toward suffering than the world assumes: not stoic indifference, not dramatic despair. In Gethsemane he wept, prayed, and asked that the cup be taken — and then chose to drink it. He showed us what it looks like to be fully human in suffering: bring it honestly to the Father, and then trust. He was not performing strength. He was demonstrating faith.',
    the_grace_in_it: 'The grace in suffering is this: God does not waste it. He is not the cause of all our pain — but he is the Redeemer of all of it. The Bible nowhere promises that suffering will be explained. It promises that it will be redeemed (Romans 8:28), that it will produce something (Romans 5:3–4), that it will be outlasted by glory (2 Corinthians 4:17), and that the One who suffered most is the One present with you in yours. Corrie ten Boom survived Ravensbrück concentration camp and wrote: "There is no pit so deep that God\'s love is not deeper still." That is not a comfort you can manufacture intellectually. It is a discovery made in the pit.',
    transformation: 'The person who has been through suffering and found Christ sufficient in it carries something that cannot be taught in a classroom. They become more compassionate with others who suffer — less likely to offer pat answers, more able to simply be present. They become less afraid of difficulty — because they have survived it and found it was not the end of God\'s presence but often its deepest expression. They become more like Jesus, who was "a man of sorrows, acquainted with grief" — and because of that, a high priest who can sympathize with every weakness.',
  },
  {
    id: 'deny-yourself',
    word: 'Deny Yourself',
    what_you_may_have_heard: 'This phrase is often preached as self-erasure — as though the goal of the Christian life is to have no desires, no preferences, no self at all. Some traditions weaponize it to keep people in unhealthy situations, insisting that any expression of personal need or boundary is selfishness. Some preach it so relentlessly that people come away feeling that their own existence is the problem. This is a serious distortion.',
    what_it_actually_means: 'The Greek word is aparneomai — the same word used of Peter\'s denial of Jesus. It means to disown, to refuse to acknowledge as having any claim. Jesus is not saying "have no self." He is saying: "Refuse to let your self have the final claim over your life." The "self" Jesus is addressing is the self that insists on its own agenda, its own safety, its own comfort, its own rights — the self that curves inward on itself. This is what Augustine called the cor incurvatum in se: the heart curved in on itself. Denying yourself is the act of un-curving that heart. It is not the elimination of personhood — it is the liberation of it. The irony of self-denial is that it produces the most genuine, free, joyful version of yourself — because you have stopped spending all your energy protecting and promoting an image that was never the real you anyway.',
    the_greek_or_hebrew: 'Greek: aparneomai (ἀπαρνέομαι) — "to deny, to disown, to refuse to acknowledge." The word implies a definite, conscious act of refusal — not a vague sentiment of humility but a decisive choice not to let self-will be the governing principle.',
    scripture: 'Luke 9:23 (CSB)',
    scriptureText: '"Then he said to them all, \'If anyone wants to follow after me, let him deny himself, take up his cross daily, and follow me.\'"',
    how_jesus_used_it: 'Jesus connected self-denial directly to taking up a cross — and in his day, a cross meant only one thing: execution. But he also immediately followed it with the most counterintuitive promise in Scripture: "For whoever wants to save his life will lose it, but whoever loses his life because of me will save it" (Luke 9:24 CSB). The paradox is not accidental. Self-denial is not loss — it is exchange. You give up the life you were trying to build on your own terms and receive a life you could not have built at all. You give up the insistence on being seen and known on your own terms, and receive being known by the One whose knowing is unconditional. The denial is the door to the gain.',
    the_grace_in_it: 'The grace in "deny yourself" is that what you are being asked to release is precisely the thing that has been exhausting you. The self that insists on being central — on being right, on being seen, on being safe, on being in control — is not a self at rest. It is a self under constant management. When you release it into the hands of God, you are not losing yourself. You are losing the burden of yourself. C.S. Lewis described it this way: "Until you have given up your self to Him, you will not have a real self."',
    transformation: 'The person who has learned to deny themselves — regularly, daily, not as a crisis moment but as a practice — becomes increasingly un-manipulable by the things the world uses to control people: flattery, threat, comparison, shame. They have released the levers. They become more generous, because they are not hoarding their resources for their own security. They become more patient, because they are not defending their own timeline. They become more free, because they are no longer imprisoned by their own image. They become more like Jesus — who "did not come to be served, but to serve and to give his life as a ransom for many" (Mark 10:45 CSB) — and who was, in that self-giving, the most fully alive human being who ever existed.',
  },
  {
    id: 'fear-of-god',
    word: 'Fear of God',
    what_you_may_have_heard: 'Some people grew up with a God who was primarily frightening — an omniscient surveillance system who catalogued every transgression and whose primary disposition toward you was disappointment or wrath. They were told to "fear God" in a way that produced terror, not trust. Others have reacted so far in the opposite direction that they have domesticated God entirely — making him into a supportive friend who never disturbs anyone\'s comfort. Both miss the mark.',
    what_it_actually_means: 'The fear of God in Scripture is not terror — but it is not mere reverence either. It is the appropriate response of a finite, sinful creature to the presence of an infinite, holy God. It includes awe, trembling, wonder, and a deep orientation toward his authority as the one before whom all things will ultimately be accounted. The remarkable thing about biblical fear of God is that it produces not paralysis but wisdom: "The fear of the Lord is the beginning of wisdom" (Proverbs 9:10 CSB). It is also strangely comforting: the One before whom the nations are as a drop from a bucket (Isaiah 40:15) is the same One who calls us children. The fear keeps the relationship honest. It prevents the casual familiarity that turns God into a divine vending machine.',
    the_greek_or_hebrew: 'Hebrew: yirah (יִרְאָה) — used for both terror and reverential awe, depending on context. The Psalms use it consistently in the sense of reverential awe that produces obedience and intimacy, not paralysis. Greek: phobos (φόβος) — can mean fear or reverence; in "fear of the Lord" contexts, the New Testament consistently uses it in the latter sense.',
    scripture: 'Proverbs 9:10 (CSB)',
    scriptureText: '"The fear of the LORD is the beginning of wisdom, and the knowledge of the Holy One is understanding."',
    how_jesus_used_it: 'Jesus did not primarily use "fear of God" language — but he did say "Don\'t fear those who kill the body but are not able to kill the soul; rather, fear him who is able to destroy both soul and body in hell" (Matthew 10:28 CSB). He drew a sharp distinction between the things we normally fear (loss, pain, death, rejection) and the One who alone deserves the kind of fear that governs all other fears. But he immediately followed this with: "Aren\'t two sparrows sold for a penny? Yet not one of them falls to the ground without your Father\'s consent. But even the hairs of your head have all been counted. So don\'t be afraid; you are worth more than many sparrows." (vv. 29–31). Fear of God rightly understood drives out every lesser fear.',
    the_grace_in_it: 'The grace in "fear of God" is that it tells you the truth about reality — and reality is ultimately good news. A God before whom every power in the universe is accountable is a God who will eventually right every wrong, vindicate every faithful person, and bring every injustice into the light. The fear of God is the foundation of justice, because it means no one gets away with anything in the end — and no faithful person goes unseen. If we do not fear God, we will fear everything else.',
    transformation: 'The person who has a proper fear of God becomes peculiarly fearless about everything else. They are not intimidated by powerful people, not controlled by public opinion, not desperate for human approval — because they answer to an audience of One whose verdict has already been given in Christ. They become more honest, because they know they cannot hide. They become more just, because they know all things will be accounted for. They become more free.',
  },
  {
    id: 'obedience',
    word: 'Obedience',
    what_you_may_have_heard: 'Obedience is perhaps the most misunderstood word in the Christian vocabulary. Some hear it as servility — the crushing of personhood in favor of blind compliance. Others have experienced it as a tool of control, used by religious leaders or abusive structures to silence legitimate questions and keep people in line. Understandably, many carry deep wounds around this word.',
    what_it_actually_means: 'The New Testament word for obedience (hupakoe) comes from two words: hupo (under) and akouo (to hear). It literally means "to hear under" — to listen in a posture of submission. True biblical obedience is not silent, mindless compliance — it is the response of a person who has genuinely heard and understood the one speaking, and who chooses to trust that voice above their own. It is what you do when you believe the Doctor\'s prescription is correct. Not because you have no questions, but because you have weighed the authority and found it trustworthy. Jesus himself, as a man, "learned obedience through what he suffered" (Hebrews 5:8 CSB) — obedience was not automatic even for him. It was a choice, made in Gethsemane.',
    the_greek_or_hebrew: 'Greek: hupakoe (ὑπακοή) — "obedience, attentive listening." Related verb: hupakouo — "to listen, to obey." The word is fundamentally relational and auditory — you obey someone whose voice you have heard and whose authority you have acknowledged.',
    scripture: 'John 14:15 (CSB)',
    scriptureText: '"If you love me, you will keep my commands."',
    how_jesus_used_it: 'Jesus connected obedience directly to love — not fear. "If you love me, keep my commands" (John 14:15). This completely reframes the motivation for obedience. It is not "obey or be punished." It is "love produces obedience naturally." The person who truly loves another person naturally wants to do what that person asks — not out of servility but out of the overflow of love. And Jesus modeled this himself: "I do nothing on my own. Just as the Father taught me, I say these things... I always do what pleases him" (John 8:28–29 CSB). Obedience for Jesus was not burden — it was the shape of his love for the Father.',
    the_grace_in_it: 'The grace in obedience is that the commands of God are designed for human flourishing. They are not arbitrary impositions — they are the Maker\'s instructions for how the creature he loves functions best. When Jesus says "Take up my yoke and learn from me" and promises that his yoke is easy and his burden light (Matthew 11:29–30 CSB), he is not describing the demands of obedience as trivial — he is promising that obedience to him leads to rest. Obedience to lesser things is what exhausts us.',
    transformation: 'The person formed by obedience — genuine, love-motivated obedience — becomes increasingly trustworthy, increasingly free, and increasingly joyful. They are not driven by the fear of being caught or the need to perform. They are moved by gratitude and love. Their obedience becomes the fruit of transformation rather than the attempt to produce it. They obey not to be made right with God — they are already right with God in Christ. They obey because they are becoming like the One who, in his obedience, redeemed the world.',
  },
  {
    id: 'repentance-salvation',
    word: 'Repentance, Baptism, and the Beginning of Salvation',
    what_you_may_have_heard: 'In many modern evangelical settings, salvation is reduced to a single moment: "pray this prayer, believe in your heart, and you\'re saved." This is not wrong exactly — but it is profoundly incomplete. It tends to produce a faith that is a one-time transaction rather than the beginning of a lifelong journey. It often disconnects conversion from community (baptism) and from the ongoing work of the Spirit (sanctification). The result is people who "got saved" but who were never taught what came next.',
    what_it_actually_means: 'Acts 2:38 gives us the clearest summary of the gospel\'s invitation: "Repent and be baptized, each of you, in the name of Jesus Christ for the forgiveness of your sins, and you will receive the gift of the Holy Spirit." Three things happen here: (1) Repentance — the decisive turn, the change of mind, the reorientation of your whole self toward God. (2) Baptism — the public, communal, embodied act of being joined to the death and resurrection of Christ and to his body. (3) The gift of the Holy Spirit — not a reward for repentance but the promised presence of God himself, who will now work the ongoing transformation that repentance begins. This is not a transaction. It is a birth — the beginning of a life, not the end of a process.',
    the_greek_or_hebrew: 'Greek: metanoia (repentance) + baptizo (baptism, immersion) + dorea (gift). The movement is: turn, be immersed, receive. Not: believe intellectually, say a prayer, start trying to be good.',
    scripture: 'Acts 2:38 (CSB)',
    scriptureText: '"Repent and be baptized, each of you, in the name of Jesus Christ for the forgiveness of your sins, and you will receive the gift of the Holy Spirit."',
    how_jesus_used_it: 'Jesus himself submitted to baptism — not because he needed repentance, but to "fulfill all righteousness" (Matthew 3:15 CSB) and to identify with the sinners he came to save. His baptism was followed immediately by the Spirit descending on him and the Father declaring his delight. This is the pattern: water, Spirit, affirmation. When Nicodemus came with questions, Jesus did not offer him a prayer to repeat. He said "Unless someone is born of water and the Spirit, he cannot enter the kingdom of God" (John 3:5 CSB) — the same pattern of external act and internal transformation working together.',
    the_grace_in_it: 'The grace in this full picture of salvation is that you are not alone in it. Repentance is a gift the Spirit enables. Baptism joins you to a community of people who will walk the road with you. The Holy Spirit is not a subsequent add-on but the promised presence of God himself — the "Paraclete," the one called alongside. The Christian life is not "I repented once, now I try hard." It is "I turned to God, was joined to his people, and now the Spirit of God is doing in me what I could never do in myself." You are not doing this alone, and you are not expected to sustain it through willpower.',
    transformation: 'The person who understands salvation as a beginning rather than a destination becomes a different kind of disciple — one who is always oriented forward, always expecting more transformation, always aware that the Spirit\'s work in them is ongoing. They repent regularly and freely, not because they lost their salvation, but because repentance is the daily rhythm of a life that is becoming more like Jesus. They return to their baptism not as a memory but as an identity: I belong to Christ. I am marked. I am not my own.',
  },
]

export const HARD_WORDS_INTRO = `These are the words that have sometimes been used against people — wielded with anger, heard in bitterness, preached without grace. They have done damage. But the words themselves are not the problem. Most of them are among the most loving things Jesus ever said. They deserve to be heard again — carefully, in context, with the compassion in which they were first spoken.`
