export interface Counterfeit {
  id: string
  name: string
  tagline: string
  color: string
  scripture: string
  scriptureText: string
  the_lie: string
  why_it_fails: string
  the_truth: string
  church_witness: string
  transformation: string
}

export const COUNTERFEITS: Counterfeit[] = [
  {
    id: 'money',
    name: 'Money & Prosperity',
    tagline: 'God wants you wealthy',
    color: '#a07020',
    scripture: 'Luke 12:15',
    scriptureText: 'Take care, and be on your guard against all covetousness, for one\'s life does not consist in the abundance of his possessions.',
    the_lie: 'The prosperity gospel teaches that financial blessing is the sign of God\'s favor — that faith, rightly applied, produces health and wealth. It is not a fringe heresy. It is the background theology of much of Western Christianity, quietly shaping how we read the Beatitudes, how we pray, and what we believe about suffering. If we are honest, most of us believe — somewhere deep — that obedience should be rewarded with a comfortable life.',
    why_it_fails: 'Jesus was homeless during his ministry. Paul wrote from prison. John the Baptist was beheaded. Eleven of the twelve apostles were martyred. If prosperity is the sign of God\'s favor, these were history\'s most spectacular failures. The prosperity gospel cannot account for the cross — the supreme act of divine love performed in absolute poverty, torture, and abandonment. It cannot explain why the people Jesus called "blessed" were the poor in spirit, the mourning, and the persecuted. It cannot survive a serious reading of Philippians 4, Hebrews 11, or 2 Corinthians 6.',
    the_truth: 'Paul writes: "I have learned, in whatever situation I am, to be content" (Philippians 4:11). Contentment is learned — it is not a feeling that follows favorable circumstances. It is a discipline, rooted in the conviction that "my God will supply every need of yours according to his riches in glory in Christ Jesus" (4:19). The blessing is not money. The blessing is the God who holds all things, whose provision is certain even when our bank account is not. "Godliness with contentment is great gain" (1 Timothy 6:6) — not because contentment produces gain, but because a person who has God and contentment together has everything.',
    church_witness: 'John Wesley gave away so much of his income that he died nearly penniless, having given tens of thousands of pounds to the poor over his lifetime. When asked why, he cited 2 Corinthians 8:9: "Though he was rich, yet for your sake he became poor." Athanasius distributed his inheritance before beginning his ministry. Francis of Assisi stripped off his wealthy father\'s clothes in the public square and walked away with nothing — and became one of the most joyful people in the history of the church. The people who have held money most loosely have almost always been the ones who found life most full.',
    transformation: 'The person freed from the prosperity gospel becomes progressively uninterested in accumulation and progressively generous — not because generosity is a strategy for getting more from God, but because they have received infinitely more than they could ever give. They discover that the more loosely they hold their possessions, the less anxious they are — because their security is not in what they own but in who owns them. They become more like Christ, who had nowhere to lay his head and called it enough.',
  },
  {
    id: 'comfort',
    name: 'Comfort & Ease',
    tagline: 'The good life is a comfortable one',
    color: '#8f9d84',
    scripture: 'Romans 5:3–4',
    scriptureText: 'We rejoice in our sufferings, knowing that suffering produces endurance, and endurance produces character, and character produces hope.',
    the_lie: 'Comfort is the ambient theology of our age. We do not preach it as a doctrine — we assume it as a right. The comfortable life, the undisturbed schedule, the frictionless existence: these have become the de facto signs of blessing. When discomfort comes, we interpret it immediately as something to be fixed, escaped, or explained as a spiritual failure. We have built a Christianity that maximizes encouragement and minimizes demand, that promises a better version of the life we already want rather than the death of the life we are living.',
    why_it_fails: 'Comfort cannot produce the things God is after in us. Paul\'s chain in Romans 5 is irreversible: suffering → endurance → character → hope. There is no shortcut. The qualities most essential to Christlikeness — patience, compassion, humility, trust, contentment — cannot be formed in the absence of the conditions that require them. A faith that has never been tested has never been proven. A love that has never been inconvenient has never been love. C.S. Lewis wrote: "God whispers to us in our pleasures, speaks in our conscience, but shouts in our pains: it is his megaphone to rouse a deaf world."',
    the_truth: 'James does not say "if you face trials" — he says "when you meet trials of various kinds, count it all joy, because you know that the testing of your faith produces steadfastness" (James 1:2–3). The comfort God offers is not the removal of hardship but his presence within it: "Even though I walk through the valley of the shadow of death, I will fear no evil, for you are with me" (Psalm 23:4). That is an infinitely better comfort than ease — because it is a comfort that hardship cannot take away. His presence is the comfort. And his presence is available in the valley in a way it is not always available on the mountain.',
    church_witness: 'William Tyndale was strangled and burned at the stake for translating the Bible into English. He had lived years of cold, poverty, and exile to do the work. His last words were reportedly: "Lord, open the king of England\'s eyes." He was not comfortable. He was not safe. He was also not bitter, not despairing, not abandoned. His letters from prison show a man of astonishing peace — because the thing he had given his life for was real. The church has always been most alive not in its comfortable seasons but in its costly ones.',
    transformation: 'The person who stops pursuing comfort as a goal becomes remarkably free — free to take risks, to serve sacrificially, to stay in hard situations longer, to love people who are difficult. They stop organizing their life around the avoidance of pain and start organizing it around the pursuit of faithfulness. And they discover, almost always, that the seasons of greatest discomfort were also the seasons of greatest growth, and that looking back, they would not trade them.',
  },
  {
    id: 'safety',
    name: 'Safety & Self-Protection',
    tagline: 'God\'s job is to keep me from harm',
    color: '#4a7062',
    scripture: 'Philippians 1:21',
    scriptureText: 'For to me to live is Christ, and to die is gain.',
    the_lie: 'We want a God who is primarily a protector — a divine insurance policy that keeps us from harm, loss, and suffering. When something goes wrong, we feel cheated: "I prayed. I tithed. I was faithful. Why did this happen?" The implicit theology is transactional: faithfulness purchases safety. When the deal falls through, faith collapses with it — because the faith was never really in God himself, but in the services we believed God provided.',
    why_it_fails: 'Stephen was stoned to death while seeing a vision of the heavens open (Acts 7). James was killed with the sword (Acts 12). Paul was beaten, shipwrecked, imprisoned, stoned, and finally beheaded. Jesus himself died at 33, betrayed by a friend, abandoned by his disciples, executed by the government. If God\'s primary job is to keep his people safe, he has a catastrophically poor track record with his most faithful servants. The disciples who followed Jesus most closely were not protected from suffering — they were sustained through it. That is a different and far more radical promise.',
    the_truth: 'Paul writes from prison with a peace that defies his circumstances: "To me to live is Christ, and to die is gain." He has been freed from the tyranny of self-preservation. Because he has already died — to self, to reputation, to comfort, to safety — nothing the empire can do to him constitutes a real threat. The person who has surrendered their life to Christ is paradoxically the freest person in the room: they have nothing to protect. The blessing is not safety. The blessing is the freedom that comes from no longer needing it.',
    church_witness: 'Perpetua was a 22-year-old nursing mother in Carthage, 203 AD. She was arrested for becoming a Christian. Her father begged her to recant. She refused. In prison, she had visions of heaven and wrote them down — and her account shows not terror but a profound peace. She wrote: "I knew I should not fight against the Lord, but against the devil." She walked into the arena willingly. Her serenity so unnerved the crowd that the gladiator who was to kill her botched the stroke out of trembling, and she guided his hand to her own throat. She was not protected from death. She was not afraid of it.',
    transformation: 'The person who releases their grip on safety becomes courageous — not in a reckless way, but in the way of someone who has a larger frame of reference. They can stay in hard places, engage difficult people, speak uncomfortable truths, and take risks for the gospel — because they are no longer primarily managing their own protection. They have entrusted that to a God who has already proven himself willing to lose everything for them. They become more like Jesus, who "when he was reviled, did not revile in return; when he suffered, he did not threaten, but continued entrusting himself to him who judges justly" (1 Peter 2:23).',
  },
  {
    id: 'ease',
    name: 'Ease & a Frictionless Life',
    tagline: 'Following Jesus should make things easier',
    color: '#7a5882',
    scripture: 'Luke 9:23',
    scriptureText: 'If anyone would come after me, let him deny himself and take up his cross daily and follow me.',
    the_lie: 'The church\'s marketing often promises that Jesus will fix your marriage, cure your addiction, stabilize your finances, and bring order to your chaotic life — and that all of this happens relatively smoothly if you just pray and obey. What gets left out is the cross. The cross is not a metaphor for mild inconvenience. It was a death instrument. Jesus was not describing a slightly improved life. He was describing a total reorientation — and the road is narrow, not because God is stingy, but because it runs through death before it reaches resurrection.',
    why_it_fails: 'The gospels consistently present following Jesus as deeply disruptive. Zacchaeus gave back four times what he had stolen. The rich young ruler was asked to sell everything — and he walked away sad. The disciples left their nets, their boats, their families. Paul counted everything he had — his education, his status, his religious credential — as "rubbish" compared to knowing Christ (Philippians 3:8). The Christian life does not get easier the further you go. It gets more demanding — and, simultaneously, more free, more joyful, more full. These are not contradictions. They are the shape of the cross.',
    the_truth: 'Jesus says his yoke is easy and his burden is light (Matthew 11:30) — but this is in contrast to the crushing burden of religious performance, not in contrast to the demands of discipleship. The yoke is light because it is shared: "Come to me… take my yoke upon you… and you will find rest for your souls." The rest is not absence of effort. It is the rest of knowing that the one pulling with you is strong enough, that you are going the right direction, and that the destination is worth the road.',
    church_witness: 'Dietrich Bonhoeffer turned down the safety of America to return to Germany and be killed. He was 39 when he was hanged at Flossenbürg, days before the end of the war. His final words, reported by a fellow prisoner, were: "This is the end — for me, the beginning of life." His life was not easy. It was profoundly, intentionally, costly. And the writings he left behind — from prison, from exile, from the underground — are among the most alive and Christ-saturated texts of the 20th century. The cross did not produce ease. It produced life.',
    transformation: 'The person who stops expecting ease becomes astonishingly resilient. They are not surprised by difficulty, not derailed by inconvenience, not shattered by loss — because they have stopped building their life on the expectation of frictionlessness. They have built it on the rock of Christ\'s finished work, which cannot be shaken. And they often discover that the very things they would have prayed away were the very things through which God was doing his deepest work.',
  },
  {
    id: 'self-protection',
    name: 'Self-Protection & Reputation',
    tagline: 'I need to guard my image',
    color: '#c06040',
    scripture: 'John 12:24–25',
    scriptureText: 'Truly, truly, I say to you, unless a grain of wheat falls into the earth and dies, it remains alone; but if it dies, it bears much fruit. Whoever loves his life loses it, and whoever hates his life in this world will keep it for eternal life.',
    the_lie: 'Self-protection is one of our deepest instincts — and it runs through almost everything we do. We manage how we appear to others. We tell our story in ways that make us look better. We avoid situations where we might fail publicly. We distance ourselves from people who reflect badly on us. We protect our reputation, our image, our brand — sometimes explicitly, sometimes so automatically we don\'t even notice it. And we call this wisdom. The Christian instinct, shaped by the cross, calls it something else.',
    why_it_fails: 'Jesus made himself of no reputation (Philippians 2:7). He was born in a stable, raised in Galilee (from which nothing good was expected), ate with prostitutes and tax collectors, was called a drunkard and a friend of sinners, died as a criminal between criminals. At every point where the management of his reputation would have demanded a different choice, he chose the other thing — the person in front of him, the truth that needed saying, the death that had to be died. His whole life is a rebuke to image management. And he explicitly calls his disciples to the same: "Woe to you when all people speak well of you" (Luke 6:26).',
    the_truth: 'The grain of wheat that refuses to fall into the ground and die "remains alone." It is self-contained, self-protected, self-preserved — and fruitless. The grain that falls and dies bears much fruit. The paradox of the kingdom is that the very instinct of self-protection that seems to preserve us actually isolates us and leaves us barren. Whereas the person who gives themselves away — in love, in service, in vulnerability, in honesty — becomes more alive, more fruitful, more fully themselves. "Whoever loses his life for my sake will find it" (Matthew 16:25).',
    church_witness: 'Augustine\'s Confessions is the most famous act of public self-exposure in the history of Christian writing. He was the Bishop of Hippo — a powerful, respected man — when he wrote in public, for everyone to read: "Our heart is restless until it finds its rest in Thee." He named his sin, his lust, his ambition, his pride, his theft. He did it not to humiliate himself but because he believed that the story of a soul found by God was more useful to the church than the story of a bishop who had always been virtuous. He was right. The Confessions is still being read 1,600 years later — because honesty has a staying power that image management never does.',
    transformation: 'The person who releases the project of self-protection becomes extraordinarily free — free to admit they were wrong, free to be honest about their struggles, free to serve without recognition, free to fail without it being a catastrophe. They stop spending enormous energy on managing how they appear and start spending that energy on actual love. They become more like Jesus: undefended, available, present, willing to be misunderstood for the sake of the person in front of them.',
  },
  {
    id: 'approval',
    name: 'Approval & Belonging',
    tagline: 'I need people to accept me',
    color: '#3b6ea8',
    scripture: 'Galatians 1:10',
    scriptureText: 'For am I now seeking the approval of man, or of God? Or am I trying to please man? If I were still trying to please man, I would not be a servant of Christ.',
    the_lie: 'The need for approval is so fundamental to how we are wired that we rarely examine it. We shape our opinions to match our tribe. We say what we think people want to hear. We avoid honest disagreement because the cost — disapproval, rejection, distance — feels too high. In the church, this produces communities where everyone agrees on the surface, no one is challenged, hard texts are avoided, and the gospel is quietly edited to remove anything that might make someone uncomfortable. We call this love. It is actually cowardice wearing the costume of kindness.',
    why_it_fails: 'Paul\'s entire apostolic ministry was marked by his willingness to be unpopular. He rebuked Peter to his face in public (Galatians 2:11). He told the Galatians that if anyone — including Paul himself — preached a different gospel, they should be accursed. He wrote to the Corinthians: "We are fools for Christ\'s sake" (1 Corinthians 4:10). Jesus told his disciples: "If the world hates you, know that it has hated me before it hated you" (John 15:18). A Christianity shaped primarily by the desire for approval cannot hold the offensive edges of the gospel — and the gospel has offensive edges. It always has.',
    the_truth: 'The extraordinary freedom of knowing you are fully known and fully loved by God is that you no longer need other people\'s approval to be okay. You are already okay — not because you\'ve earned it, but because the verdict has already been pronounced over you in Christ. Righteousness is imputed; acceptance is settled; belonging is secured. That is the foundation from which honest, courageous, kind speech becomes possible. You can tell the truth — including hard truth — from a position of security rather than anxiety, because your security does not depend on how the person in the room responds.',
    church_witness: 'Martin Luther was excommunicated. John Calvin was exiled from Geneva. Athanasius was exiled five times. Tyndale was burned. Polycarp was burned. The pattern is consistent: the people in church history who most clearly held the gospel were frequently the most unpopular in their own time. And they are the ones we still read, still quote, still build on. The approval of their generation was not what mattered. What mattered was faithfulness to the One who will outlast every generation.',
    transformation: 'The person who is increasingly secure in God\'s approval becomes increasingly honest, increasingly courageous, and increasingly free in relationships. They can love people without needing anything back. They can disagree without being disagreeable. They can speak truth without being threatened by the response. They become more like Paul — someone who could write "I have learned, in whatever situation I am, to be content" (Philippians 4:11) — and mean it, not because circumstances were favorable, but because approval had found its proper source.',
  },
  {
    id: 'control',
    name: 'Control & Certainty',
    tagline: 'God should make my path clear and predictable',
    color: '#2d7055',
    scripture: 'Proverbs 3:5–6',
    scriptureText: 'Trust in the Lord with all your heart, and do not lean on your own understanding. In all your ways acknowledge him, and he will make straight your paths.',
    the_lie: 'We want a God who gives detailed instructions — a celestial GPS that recalculates when we make a mistake and always tells us exactly what to do next. We want certainty about our future, our decisions, our callings, our relationships. When clarity doesn\'t come, we panic or we manufacture it. We read guidance into circumstances, feelings, and coincidences. We cannot rest in the not-yet-knowing. The need for control — to have things resolved, mapped, and certain — is one of the great enemies of faith.',
    why_it_fails: 'Abraham left Ur "not knowing where he was going" (Hebrews 11:8). Moses led Israel into the wilderness without a roadmap. The disciples were sent out with instructions not to bring a bag or extra sandals (Luke 10:4). Paul\'s missionary journeys were repeatedly redirected by the Spirit in ways he did not anticipate (Acts 16:6–7). The whole structure of the Christian life is trust — which is only meaningful in the absence of certainty. If you can see the whole road, you don\'t need to trust the guide. Faith is "the conviction of things not seen" (Hebrews 11:1). Certainty and faith are not the same thing.',
    the_truth: 'Proverbs 3 does not promise that God will make the path obvious. It promises that if we trust him with our whole heart and acknowledge him in all our ways, he will make our paths straight — which means he will ensure we arrive where we are supposed to arrive, even if the road surprises us. The blessing is not control. The blessing is a Guide who is trustworthy, who has been faithful before, and who is committed to bringing us through. That is immeasurably better than a map — because maps don\'t know you, don\'t love you, and can\'t carry you when you\'re too tired to read them.',
    church_witness: 'Hudson Taylor, founder of the China Inland Mission, wrote: "I have found that there are three stages in every great work of God: first, it is impossible, then it is difficult, then it is done." He sailed to China without guaranteed support, without a plan, without certainty — and opened the interior of China to the gospel. George Müller ran orphanages in Bristol on faith alone — no fundraising, no appeals — and cared for over 10,000 children over his lifetime. His journals are records of one uncertainty after another resolved by a faithful God. The people who trusted God most completely were, almost always, the ones who controlled least.',
    transformation: 'The person who releases the need for control becomes progressively more peaceful — because peace was never contingent on certainty. They can hold open questions without being undone by them. They can make decisions without guarantees. They can enter situations without knowing how they will end. They develop what Paul calls "the peace of God, which surpasses all understanding" (Philippians 4:7) — a peace that is inexplicable precisely because the circumstances don\'t warrant it. And they become more like Jesus, who "entrusted himself to him who judges justly" (1 Peter 2:23) even on the cross.',
  },
  {
    id: 'christ',
    name: 'Christ Is the Blessing',
    tagline: 'Everything else is shadow; he is the substance',
    color: '#1e3f6b',
    scripture: 'Philippians 3:7–8',
    scriptureText: 'But whatever gain I had, I counted as loss for the sake of Christ. Indeed, I count everything as loss because of the surpassing worth of knowing Christ Jesus my Lord. For his sake I have suffered the loss of all things and count them as rubbish, in order that I may gain Christ.',
    the_lie: 'The deepest version of the prosperity gospel is the one that doesn\'t know it is one — where we use the language of following Christ but mean, underneath, that we are following him in order to get a better version of the life we already wanted. Where Jesus is instrumental — the means to what we really want: health, family harmony, purpose, inner peace, a good reputation. Where we come to him not because he is worth everything but because we believe he will give us the other things we think we need.',
    why_it_fails: 'Paul had the credentials, the education, the religious standing, the social respect. And he counted it all "rubbish." The Greek word — skybala — is coarser than most translations suggest. It means dung, garbage, waste. Paul is not wistfully releasing good things for better ones. He is saying that compared to knowing Christ, everything else he ever valued belongs in the bin. This is not asceticism — it is clarity. He has tasted something that makes everything else taste like nothing by comparison. The tragedy is not losing worldly goods for Christ\'s sake. The tragedy is spending a life accumulating the rubbish.',
    the_truth: 'Christ is not the path to the blessing. He is the blessing. "For in him the whole fullness of deity dwells bodily, and you have been filled in him" (Colossians 2:9–10). Everything we are searching for — security, love, purpose, belonging, beauty, truth, life itself — is found in him and not anywhere else in a form that will last. Not in money (which rusts), not in relationships (which can be lost), not in reputation (which is others\' construction of you), not in comfort (which ends), not in safety (which is never guaranteed). Only in Christ, who is "the same yesterday and today and forever" (Hebrews 13:8), and who holds everything together (Colossians 1:17), is the fullness of what we seek actually available.',
    church_witness: 'Jim Elliot, killed by the Auca people he had gone to reach with the gospel in 1956, wrote in his journal years before his death: "He is no fool who gives what he cannot keep to gain what he cannot lose." He lost his life at 28 in a jungle clearing. His wife Elisabeth stayed, learned the language, and eventually led many of the people who killed her husband to Christ. Both of them had found what Paul had found: that Christ is worth more than life. Not as an abstract doctrine — as a lived conviction, tested in the hardest possible way. The blessing is not a long life, a safe life, or a comfortable life. The blessing is knowing the One who is life.',
    transformation: 'The person who has genuinely found Christ to be the blessing — not just doctrinally but experientially, in the bones — becomes the most dangerous and the most free person in the room. They cannot be threatened, because they have nothing to protect. They cannot be bought, because they have the only thing worth having. They cannot be stopped by comfort or distracted by ease. They are increasingly single-minded in the best possible sense: one thing have I desired of the Lord; that will I seek after (Psalm 27:4). And they become, slowly, beautifully, the most Christlike thing the people around them have ever seen — because Christ is not only the destination but the One doing the forming.',
  },
]

export const CAPSTONE = {
  title: 'The Fruit Is Not the Goal',
  body: `Jesus did not say "seek the fruit and the Kingdom will be added." He said "seek first the Kingdom of God and his righteousness, and all these things will be added to you" (Matthew 6:33). The order is irreversible.

The fruit of the Spirit — love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control (Galatians 5:22–23) — is not a program to achieve. It is the natural overflow of a life connected to the vine. The branch does not strain to produce fruit. It abides. And abiding in Christ — seeking him above money, safety, ease, comfort, control, and approval — is the whole life.

The doctrine is the game. The doctrine tells us what is real: who God is, what he has done in Christ, what has been accomplished, what has been promised, and where history is going. The fruit is what happens to a person who actually believes the doctrine — who lets it reach below the level of information into the level of identity and desire. Doctrine without fruit is dead orthodoxy. Fruit without doctrine is rootless sentimentalism. Together, in a person who is genuinely with Jesus, learning from Jesus, to become like Jesus — together they are the Christian life.

He is the blessing. Everything else is gift.`
}
